[package]
name = "bfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bfc-ir = { git = "https://github.com/Alextopher/bfc-ir.git", branch = "master" }
